### ISSUE TITLE
Strange Problems

### ISSUE THREAD

**Issue by H4nSolo** [MarkCavalli/rageserver#1]
hiho, i am newbie in RageMP servers but i will still learning ;)
I have downloaded a Project on the RageMP Forum (https://rage.mp/forums/topic/1559-open-source-role-play-server/) and configurate it. (mysql data are correct)
But always when i connected to the local Server, he didnt create a user entry in the Database and i can see in the server console that he query the Database correctly.
A Register or Login Window doens't opened also after connect to the local Server.

What i do wrong?

My Steps:
1. Download Project from Github an paste it on a fresh clear RageMP Server
2. Install Mysql Modul over npm ("npm install mysql")
3. Edit sMisc.js for correct mysql Connection Datas
4. Create manuell the Table for the Server (like Forum ;) )
5. Start the Server and connect via RageMP Client to the Server

**Comment by MarkCavalli** [comment]
Okay, lets try solve it. =)
1. "DATABASE IS WORKING"   Is that message shows on server start?
(If it shows, looks like your db "rpserver" works correctly).

today i put this server to vps hosting, so will take all your steps =).

Maybe problem is your table "users' is empty.
Try manually add one user and test it!
I'll be wait for your answer. =)

**Comment by H4nSolo** [comment]
Hello MarkCavalli,

the message "DATABASE IS WORKING" appears in the server console.
The database is empty as you already mentioned.
Unfortunately, I do not know what encryption you have chosen for the password parameter, so I can also manually insert no record which could allow me a possible login.

In addition, I would like to say that if I put the server fresh, even when you first enter, no registration or login page get but I can move freely on the server.
The map, where according to map file at least 10 - 50 symbols should be recognizable, remains empty.

I also tried running the server under linux ubuntu 1604 LTS 64bit on a dedicated root server, but as soon as I transferred the files from Github and ran the settings as well as npm install, I get it
only start a "memory access error (memory image created)"


I hope you can start with the error descriptions and give me more help.

**Comment by MarkCavalli** [comment]
Just now tested server with empty db. So, i spawn on the shore, thats all =).
Then i add one string in db (without password, just random username) and all works fine.
When db is empty, mysql returns empty object, so variable in code own "undefined" type and register form dont start.
You can look at encryption at sLogin file. =)

Just add string with random params and then normally register your account from CEF =)

**Comment by MarkCavalli** [comment]
How is going your development? =)
I rewrited some sLogin logic. Now it will be work fine with big size db.
Also you dont need add empty user anymore =)

**Comment by H4nSolo** [comment]
Thank you very much
If I'm at home right away, I'll try it out and give you some feedback on it.

**Comment by H4nSolo** [comment]
Here is the promised update:

After creating a clean bare server, inserting things from Github and editing sMisc.js, I got the login window. ;)
Nice is now that you have debugger information built into the console and there is now a server log.

Based on the debug information in the server console, I found that you had added 2 more parameters in the database because of the "login time" and the "last login", which I unfortunately had overlooked until recently.

But now everything works and I was able to register and register immediately.
Later I will try to get the whole thing running on a linux root.


I'm curious what you want to implement next.


Proposals:
 - Please also enter changes directly on the forum page with any notes when last edited;)
 - debug information in the server console, turn it on or off, preferably via a central config.js
 - At the ATM you should have the possibility to use an interaction to get into the bank menu. An environment-oriented load (if one is only directly in front of the ATM) I find personally annoying if you might just pass it and suddenly the menu opens.

best regards

H4nSolo

**Comment by MarkCavalli** [comment]
Hello =).
You can change log level in sMisc:
`categories: { default: { appenders: ['file', 'console'], level: 'debug' } }`
New Update already on the forum.
