### ISSUE TITLE
New RageMP broke the resource

### ISSUE THREAD

**Issue by diegobh** [MarkCavalli/rageserver#104]
I updated the ragemp and noticed that a lot of things just broke... I've no idea how fix then, could u or anyone give me any help, please? It was all working wonderfully before the update lol.

Things that i noticed breaks:
- Server crash after enter the colshape to get the job. Error:
`Object reference not set to an instance of an object.
Object reference not set to an instance of an object.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at void Bootstrapper.EventInternalClass.OnPlayerEnterColshape(ushort playerId, ushort colshapeId)`
- Keybinds are just strange. Can't toggle engine with numkey-0 but can toggle lock with L key o.O The keys I mapped to open the vehicles windows aren't working too. I can use the numpad-9 to open right front window, but the others numkeys-7 (driver's window) , numkeys-1 (back left window)  and numkey-3 (back right window) aren't working. I press and nothing happens...

Thank you!

**Comment by MarkCavalli** [comment]
I will take a look on this

**Comment by MarkCavalli** [comment]
On my pc all working fine. Exception you paste is from c# language, make sure you disabled C# in conf.json. Also, in this gamemode vehicle lock is toggling on numpad + key. Seems you have conflict with some other gamemode

**Comment by diegobh** [comment]
> On my pc all working fine. Exception you paste is from c# language, make sure you disabled C# in conf.json. Also, in this gamemode vehicle lock is toggling on numpad + key. Seems you have conflict with some other gamemode

Thank you for help.
O.O i disabled the c# like u suggested and it fixed the server crash. The strange is that i just copy and paste the resource folder to a new RAGEMP updated folder. The new version of ragemp broke something lol. But im not using c# so no problem it be disabled ;)

The Num+ key never worked here, no idea the reason. Maybe because my keyboard layout is Brazil ABNT (who knews) :P So i just add the same key map to numpad 0. You can check my keymappings here: https://pastebin.com/Dkw8Zcvm
The code is inside the constructor of the file: sVehicleSingletone.js

My cKeys.js is here: https://pastebin.com/ZMKrGw3Z

And my sVechicle.js: https://pastebin.com/bRMYYd1p

The keymaps that aren't working are:
- Toggle Engine (Numpad+ or Numpad0)
- Toggle Windows (Numpad-1, Numpad-3, Numpad-7 and Numpad-9)
 
Anyone could help, please?
Thank you very much!

**Comment by diegobh** [comment]
@MarkCavalli  I found the error :D

With the new rage version the seats changed, so you have to fix it in sPlayer.js :

> player.isDriver = function() {
            //if (!this.vehicle || this.seat !== -1) return false;
            if (!this.vehicle || this.seat !== 0) return false;
            return true;
        }

Now it starts with 0 instead of -1.
With just this little change all my key mappings works again.
