### ISSUE TITLE
All CluckIn Bell destinations marked on the map

### ISSUE THREAD

**Issue by diegobh** [MarkCavalli/rageserver#105]
Any idea how hide those destinations been marked on the map, please? 
![](https://iili.io/J0Wgl2.jpg)
It would be better mark just the one that you have to deliver at the time.

Thank you very much ;)

**Comment by MarkCavalli** [comment]
Yes this job need to be rewritten =)

**Comment by diegobh** [comment]
> Yes this job need to be rewritten =)

I made: https://github.com/MarkCavalli/rageserver/pull/107

Wish you like it ;)

**Comment by MarkCavalli** [comment]
Thank you for your big job =)
