### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by GeekbeeGER** [MarkCavalli/rageserver#18]
E:\RP_SRV\server-files>npm i
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

maybe any think wrong but were ?

**Comment by GeekbeeGER** [comment]
Console Say

(node:7284) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: s.getMailAdress is not a function
(node:7284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by MarkCavalli** [comment]
first warns its okay

**Comment by MarkCavalli** [comment]
Are you pasted right mail?
```
function getMailAdress() {
    return 'Open Source RP server <youmail@gmail.com>';
}
```

**Comment by GeekbeeGER** [comment]
"use strict"

const nodemailer = require("nodemailer");

const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: 'myemail@gmail.com',
        pass: 'password'
    }
});

transporter.verify(function(error, success) {
	if (error) {
		console.log(error);
	} 
	else {
		console.log('EMAIL SERVER READY!');
	}
 });


function sendMail(message) {
	transporter.sendMail(message, (err, info) => {
        if (err) {
            console.log('Error occurred. ' + err.message);
            return process.exit(1);
		}
    });
}
exports.sendMail = sendMail;

copy & past only i change the mail and password to my gmail
