### ISSUE TITLE
is rage.mp down?

### ISSUE THREAD

**Issue by edouardlicn** [MarkCavalli/rageserver#20]
it redirect to gta network automatically.

**Comment by MarkCavalli** [comment]
+

**Comment by edouardlicn** [comment]
looks like no one aks that on gtanetwork,it seems strange.

**Comment by MarkCavalli** [comment]
maybe smth wrong with hosting. lets wait

**Comment by edouardlicn** [comment]
it make me a great confuse that if sothing happen like this we wont be able to down main server files.

**Comment by DkVagabonden** [comment]
They wrote on their discord. That there is issues with their host. But that their cdn is still up and serverlist.

**Comment by Faui2203** [comment]
Hello Mark - it seems you pretty good with Javascript - I have some questions - Can you give me your skype or email pls? Thanks alot

**Comment by MarkCavalli** [comment]
evo.lu skype

**Comment by edouardlicn** [comment]
do u have line?

**Comment by MarkCavalli** [comment]
no, i dont know what is that

**Comment by edouardlicn** [comment]
a phone app like skype

**Comment by edouardlicn** [comment]
i add an user with cat avata,is that u?
