### ISSUE TITLE
still with problem with register.

### ISSUE THREAD

**Issue by edouardlicn** [MarkCavalli/rageserver#21]
(node:11698) UnhandledPromiseRejectionWarning: TypeError: i.getMailAdress is not a function
    at Object.sendCode (/mnt/data/rage_mp01/ragemp-srv/packages/RP/index.js:1:89154)
    at Object.trySendCode (/mnt/data/rage_mp01/ragemp-srv/packages/RP/index.js:1:88873)
    at Object.tryGetCodeToRegister (/mnt/data/rage_mp01/ragemp-srv/packages/RP/index.js:1:88804)
    at <anonymous>
(node:11698) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11698) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by edouardlicn** [comment]
and when login

(node:12011) UnhandledPromiseRejectionWarning: TypeError: i.getMailAdress is not a function
    at Object.sendCode (/mnt/data/rage_mp01/ragemp-srv/packages/RP/index.js:1:89154)
    at Object.trySendCode (/mnt/data/rage_mp01/ragemp-srv/packages/RP/index.js:1:88873)
    at Object.tryGetCodeToLogin (/mnt/data/rage_mp01/ragemp-srv/packages/RP/index.js:1:92299)
    at Object.sLogin-TryGetCodeToLogin [as self] (/mnt/data/rage_mp01/ragemp-srv/packages/RP/index.js:1:88448)
    at Object.fire (<anonymous>:721:8)
    at eval (eval at add (unknown source), <anonymous>:3:11)
(node:12011) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12011) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by MarkCavalli** [comment]
```
function getMailAdress() {
    return 'Open Source RP server <youmail@gmail.com>';
}
exports.getMailAdress = getMailAdress;
```
Did you pasted email like this?

**Comment by edouardlicn** [comment]
paste at where?

**Comment by edouardlicn** [comment]
oic ,done.test a while.

**Comment by edouardlicn** [comment]
new problem

because my mail provider need user and password setting,so i write below

> const transporter = nodemailer.createTransport({
        host: 'smtp.qq.com',
        port: 465,
        secure: true, // true for 465, false for other ports
        auth: {
            user: '2361094570', // generated ethereal user
            pass: '*****' // generated ethereal password
        }
});

then when i login console said 
Error occurred. Mail command failed: 501 mail from address must be same as authorization user
it seems back to that i need to mod your code to confirm mailfrom content.

**Comment by MarkCavalli** [comment]
`user: '2361094570@qq.com', `
?

**Comment by edouardlicn** [comment]
not working.

**Comment by MarkCavalli** [comment]
Okay, do changes in code and send me working variant, i will check

**Comment by MarkCavalli** [comment]
not a pull request =)

**Comment by edouardlicn** [comment]
btw,why login need email auth?

**Comment by MarkCavalli** [comment]
If ip changed, email get login code. Some kind of protection

**Comment by edouardlicn** [comment]
o i understand.i did not change the "from" setting in smail file.it works.it need to add some help.

**Comment by edouardlicn** [comment]
i suggest to change it into generating a code.email is quite annoy.or should add a seletion to open/close this function.

**Comment by MarkCavalli** [comment]
okay when user with other ip try to login into account what we should do?

**Comment by edouardlicn** [comment]
it is his/her fault :)

**Comment by MarkCavalli** [comment]
And when his/her account will be hacked, he/she will ask you to restore all data =).
If hackers sell a business, for example, and someone will buy it - a complicate situation...
You better tell me, what wrong with current system? Do you have some problems?

**Comment by edouardlicn** [comment]
no problem now :)

that is just suggestion for user's  convenion.

i will add some helps on smail files.

**Comment by MarkCavalli** [comment]
okay =)
