### ISSUE TITLE
Nodemailer issue

### ISSUE THREAD

**Issue by TroublesMader** [MarkCavalli/rageserver#51]
I know that there already was such issue, but nobody posted the solution and I was unable to find it by myself.
I've set up the server and everything works fine except mailer module. You can login and play, but server closes if you try to register (when you press button "Get code") with the line: "Error occured. self signed certificate in certificate chain".
This message you have in server console on startup:

```
{ Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1036:34)
    at TLSSocket.emit (events.js:159:13)
    at TLSSocket._finishInit (_tls_wrap.js:637:8) code: 'ESOCKET', command: 'CONN' }
```

I have tried different  email services (known for nodemailer), different settings and accounts of gmail etc. The same.

Maybe It's cause I'm starting server locally with local IP?

I've found 2 solutions in web:
1.  Try adding this: `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";` It tells Node to accept self signed certificates.
2. You can use this as well:
```
nodemailer.createTransport({
    host:'...',
    ...,
    tls:{
        rejectUnauthorized: false
    }
`});
```
But I couldn't implement this. Maybe you can advice how to disable correctly this check for certificates.
I'm sure this is spread problem during setting up your tremendous server.

**Comment by MarkCavalli** [comment]
Thank you for detail feedback, I've added 2 step into sMailer.example

**Comment by TroublesMader** [comment]
Great, now everything works well 👍

**Comment by nr2019** [comment]
Thank you. rejectUnauthorized: false resolve the all morning problem !

**Comment by kiki199331** [comment]
Did you check the host port? (if you dose not assign , 'Nodemailer' default port is 587)
you can read this article and check the which port you should use :
https://www.mailgun.com/blog/which-smtp-port-understanding-ports-25-465-587

**Comment by felipeperezsanchez** [comment]
thanx!!!

**Comment by MrMulaomerovic** [comment]
I have this problem in 2021 :), i am trying to solve, and still have a problem and a message "Proccess not define" although I am check my environment variable 100x
