### ISSUE TITLE
Can not set Hospital Leader 

### ISSUE THREAD

**Issue by SupperCraft5000** [MarkCavalli/rageserver#52]
When i try the command "/sethospitalleader" or "/sethospitalleader 1" then nothing happend the Database is not changed. And there is a error on the console.
`(node:5356) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: s.getAdminLvl is not a function (node:5356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. (node:5356) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: s.getAdminLvl is not a function`

**Comment by MarkCavalli** [comment]
getAdminLvl replace with player.adminlvl < 1

**Comment by SupperCraft5000** [comment]
in which file and line ?

**Comment by TroublesMader** [comment]
> in which file and line ?

There is search trhough files, in Sublime Text 3 for example..
app\server\Factions\Hospital\sHospital.js:211
app\server\Factions\sFaction.js:140

**Comment by SupperCraft5000** [comment]
Getting still errors

`(node:5116) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): ReferenceError: n is not defined`

**Comment by TroublesMader** [comment]
that's strange but I have a bit different node code:

```
(node:18736) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: n is not defined
(node:18736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
