### ISSUE TITLE
Inventory & 

### ISSUE THREAD

**Issue by DarylDixonLS** [MarkCavalli/rageserver#54]
Grüße ... Wo werden die angesammelten Orangen (Job) abgespeichert? Der Script hat "kein" Spieler Inventar! Oder?
Wird es später noch ein Tuningshop/Waffengeschäft geben?

Greetings ... Where are the accumulated oranges (job) stored? The script has "no" player inventory! Or?
Will there be a tuning shop / gun shop later?

**Comment by MarkCavalli** [comment]
Hello DarylDixonLS. This is complete gamemode and it will not have any updates. You can take a look of it and try to build your gamemode from 0.
