### ISSUE TITLE
Hello! Some questions

### ISSUE THREAD

**Issue by NorthFailer** [MarkCavalli/rageserver#56]
Hello, sorry for offtop @MarkCavalli .

I just want to ask you some questions:
Are you Russian?
And if the answer is yes - do you know who Farbid_Halifa is?(samp)

It's wierd, but there is a chance that i can know you, but missed contacts some years ago :)

**Comment by MarkCavalli** [comment]
Yes, i'm russian, but i dont remember Farbid_Halifa =)

**Comment by NorthFailer** [comment]
Возможно ты играл в SAMP:RP лет так 5-7 назад под таким же ником?

**Comment by MarkCavalli** [comment]
Да, на адвансе играл на реде и грине. Но я встречал еще людей с такой фамилией

**Comment by NorthFailer** [comment]
Значит это тв Марк) Меня зовут Саша. North_Failer основа была, играли вместе. Farbid_Halifa это ты зря забыл )) создавали бомжей и играли с Lua скриптами(хаками).
Ты у меня в ВК был, пока тебе страницу не заблокировали.
Если у тебя новый vk есть, то по такому же нику как на github найди меня, или в telegram(тот же ник)

**Comment by NorthFailer** [comment]
Либо дай какой-либо свой контакт для связи, в профиле у тебя ничего не указано к сожалению
