### ISSUE TITLE
npm i errors

### ISSUE THREAD

**Issue by valeopay** [MarkCavalli/rageserver#61]
Hi, 

i have some errors after npm i

C:\gtaserver\server-files>npm i
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm ERR! code EINTEGRITY
npm ERR! sha1-qJ+7Ig9c4l7FboxKqKT9e1sNKf4= integrity checksum failed when using sha1: wanted sha1-qJ+7Ig9c4l7FboxKqKT9e1sNKf4= but got sha512-U2ALcoAHvA1oO2xOreyHvtkQ+IELqDG2WVWRI1GH/XEmmfGIOalnM5MU5Dd2ITyWfr3m6kNqXiy8XuYyd4wKJw== sha1-NjyatchZ2p0tb7kBtk2YCWYYEYQ=. (2232 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-03-31T00_45_36_804Z-debug.log

C:\gtaserver\server-files>

**Comment by DrakBornAzn** [comment]
Hi ! delete node_modules , do a " npm i cryptiles@latest " and after that a npm i !

**Comment by Dan-B1** [comment]
@DrakBornAzn would it be possible to add you on discord?

**Comment by DrakBornAzn** [comment]
Sure ! Give me yours !
