### ISSUE TITLE
issues adding external client packages

### ISSUE THREAD

**Issue by hailjake** [MarkCavalli/rageserver#62]
I tried to add noClip and nativeUI and afew other and none seem to work, would be awesome to add some documentation on this!

**Comment by hailjake** [comment]
i was hoping to get some clarification on this but ok, i also have a branch where i converted all css to scss and some redone UI's for car purchasing etc. if you are interested, great work on the base of this framework btw as i said above the only issue im facing is getting 3rd party packages working, i followed the pattern of the betternotifs with no luck.

**Comment by MarkCavalli** [comment]
Well, hailjake, you should understand, i provide only this mod and i dont know is it possible implement custom mods or not. Yesterday i updated outdated packages so you can try to install it again
