### ISSUE TITLE
Numpad + does not work

### ISSUE THREAD

**Issue by Kalle801** [MarkCavalli/rageserver#64]
Good evening :)

I noticed that the Vehicle button (numpad+) does not work.

Best Regards and Thanks in advance.

**Comment by jordansitbon** [comment]
Up

**Comment by pyramidice** [comment]
Also having this issue.

**Comment by Kalle801** [comment]
You can fix it in the index.js. I forgot to write it here Regards.

**Comment by MarkCavalli** [comment]
Its worked 3 months ago. Maybe it's a CEF bug, need test

**Comment by Germanrazor** [comment]
can you tell more about, how to fix ?

**Comment by Germanrazor** [comment]
ok, i found a workaround after 2 hours...
in client_packages\indes.js
is

C.bind(d,function(){mp.gui.cursor.visible||mp.events.callRemote("sKeys-Num+")})

but it must be

C.bind(d,!1,function(){mp.gui.cursor.visible||mp.events.callRemote("sKeys-Num+")})

this is only temporary, when you build the server with "npm run build" it overrides the config

sorry for my bad english :(

hope that helps

**Comment by MarkCavalli** [comment]
You need to fix it in cKeys file and then rebuild

**Comment by Germanrazor** [comment]
ah, ok, I found the mistake..

it was

keys.bind(k.ADD_KEY, function() {
    if (mp.gui.cursor.visible) return;
    mp.events.callRemote('sKeys-Num+');
});

instead of

it was

keys.bind(k.ADD_KEY, false, function() {
    if (mp.gui.cursor.visible) return;
    mp.events.callRemote('sKeys-Num+');
});

thank you for your help
