### ISSUE TITLE
German Translation GasStation

### ISSUE THREAD

**Issue by GeekbeeGER** [MarkCavalli/rageserver#7]
doneText = "Erledigt!";
enterText = `Dr&uuml;cke ~b~E ~s~um das Tankstellenmenü zu &ouml;ffnen`;
priceForLitreText = "Preis pro Liter:";
goodJourneyText = "Gute weiter Reise!";
offEngineText = "Bitte schalte den Motor ab!"

**Comment by MarkCavalli** [comment]
Done, thanks
