### ISSUE TITLE
Hi guys i need help

### ISSUE THREAD

**Issue by CalipoPA** [MarkCavalli/rageserver#70]
**When i try start npm run build i get this error**
C:\Users\Dorado>npm run build
npm ERR! path C:\Users\Dorado\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Dorado\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dorado\AppData\Roaming\npm-cache\_logs\2019-05-30T05_36_51_638Z-debug.log

**How i can fix it?**
**Thanks :D**

**Comment by MarkCavalli** [comment]
C:\Users\Dorado\package.json
Wrong folder

**Comment by CalipoPA** [comment]
what folder need go?

**Comment by diegoaguiar90** [comment]
the main of your project, e.g. C:/RAGEMP/server-files
