### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by anazhd** [MarkCavalli/rageserver#9]
I already setup everything accordingly but when I'm connected to the server it shows 404 Not Found on top left corner of the screen. No login screen.

client_packages/Browsers have everything it should have.
https://imgur.com/HD4p9T7

Nothing weird on the console.
https://imgur.com/64miEN9

NodeJS 8.x
MySQL 5.7

**Comment by MarkCavalli** [comment]
Yep, i fixed that error yesterday, please, redownload package, now it must be ok

**Comment by anazhd** [comment]
Is it because of the Browsers is not in the RP folder?

I noticed in linux it's `client_packages/RP/Browsers` but on Windows it is `client_packages/Browsers`

Anyway thank you.
